pipeline {
    agent any

    stages {
        stage('Git CheckOut') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '13b26195-9c74-467c-90f7-0105adf854f4', url: 'https://github.com/xiaohongwu0520/CICDTest.git']]])
            }
        }
        stage('Build') {
            steps {
                echo 'Build'
            }
        }
        stage('Test') {
            steps {
                echo 'Test'
            }
        }
    }
}
